ALTER TABLE atm_profiles DROP COLUMN IF EXISTS atm_name;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS city;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS state;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS commissions;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS seo;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS cash_fee;
ALTER TABLE atm_profiles DROP COLUMN IF EXISTS rent;

ALTER TABLE atm_profiles ADD COLUMN IF NOT EXISTS location_name TEXT;
ALTER TABLE atm_profiles ADD COLUMN IF NOT EXISTS sales_rep_id UUID REFERENCES sales_reps(id) ON DELETE SET NULL;
ALTER TABLE atm_profiles ADD COLUMN IF NOT EXISTS monthly_rent DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE atm_profiles ADD COLUMN IF NOT EXISTS monthly_cash_fee DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE atm_profiles ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
