-- Add new columns to commissions table for better transparency
ALTER TABLE commissions
ADD COLUMN IF NOT EXISTS total_sales DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_fees DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS rent DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS mgmt_rps DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS mgmt_rep DECIMAL(12,2) NOT NULL DEFAULT 0;
